### ISSUE TITLE
cb is not a function

### ISSUE THREAD

**Issue by coltongit** [sidorares/yandex-translate#22]
I get `cb is not a function` when I try to use this API, and the error logs show that it occurs on line 14. Could this be easily fixed?

**Comment by sidorares** [comment]
I think it needs to fixed on your side. Function accepts exactly 3 parameters and 3rd must be a function. Can you show how you are using this library?

**Comment by coltongit** [comment]
> I think it needs to fixed on your side. Function accepts exactly 3 parameters and 3rd must be a function. Can you show how you are using this library?

I'm using it like this:
```js
translate.translate(text,format,from-to,function(err,text){
}```
Is this the way I should be using it?

**Comment by coltongit** [comment]
I've also used this format and it didn't work either:
```js
translate.translate(text,from-to,function(err,text){
}

**Comment by sidorares** [comment]
must be exactly 3 arguments - `text, {from, to}, callback`

**Comment by coltongit** [comment]
OK. I tried what you said to do and it seems to have fixed the problem. Thanks for the help. I'll go ahead and close this now.
