### ISSUE TITLE
alphabetically order issue

### ISSUE THREAD

**Issue by mushtaq99** [sidorares/yandex-translate#24]
how to  alphabetically  order the languages list.

**Comment by sidorares** [comment]
which list @mushtaq99  ?

**Comment by mushtaq99** [comment]
list of available languages

**Comment by mushtaq99** [comment]
setLanguagesArrays(languagesArrays);
        languages = languages;
        return languages;

**Comment by mushtaq99** [comment]
return languages list  i mean chines language show at the end of the list

**Comment by mushtaq99** [comment]
i want to show them in Alphabetical order

**Comment by sidorares** [comment]
Just sort them ? `return languages.sort((l1, l2) => l1 > l2 ? 1 : -1))` ?

**Comment by mushtaq99** [comment]
let me check it ..

**Comment by mushtaq99** [comment]
can not resolve method .sort

**Comment by mushtaq99** [comment]
public static HashMap<String, String> getAllLanguages() {
        int i;
        Locale[] loc = Locale.getAvailableLocales();
        Log.d("##########", "getAllLanguages: " + loc.length);
        for (i = 0; i < loc.length; i++) {
            if (Config.getYnLanguages().getHashMap().containsKey(loc[i].getDisplayLanguage())) {
                languages.put(loc[i].getLanguage(), loc[i].getDisplayLanguage());
                languagesArrays.add(new LanguagesArray(loc[i].getDisplayLanguage(), loc[i].getLanguage(), loc[i].getDisplayName(), loc[i]));
                Log.d(TAG, "getAllLanguages: " + languagesArrays.size());
            }
        }
        for (i = 0; i < languagesArrays.size(); i++) {
            for (int j = i + 1; j < languagesArrays.size(); j++) {
                if (((LanguagesArray) languagesArrays.get(i)).getLanguageName().equals(((LanguagesArray) languagesArrays.get(j)).getLanguageName())) {
                    Log.d("#########", "getAllLanguages: "+((LanguagesArray) languagesArrays.get(i)).getLanguageName());
                    ((LanguagesArray) languagesArrays.get(j)).setDuplicate(true);
                }
            }
        }
        Iterator<LanguagesArray> iterator = languagesArrays.iterator();
        while (iterator.hasNext()) {
            if (((LanguagesArray) iterator.next()).isDuplicate()) {
                iterator.remove();
            }
        }
        setLanguagesArrays(languagesArrays);
        languages = languages;
        return languages;
//        return languages.sort((l1, l2) => l1 > l2 ? 1 : -1);
    }

**Comment by mushtaq99** [comment]
my code

**Comment by mushtaq99** [comment]
static HashMap<String, String> languages = new HashMap();

**Comment by sidorares** [comment]
I think the code has nothing to do with this library ( Is that C# ? )

**Comment by mushtaq99** [comment]
languages is not array actually it is HashMap

**Comment by mushtaq99** [comment]
no its android

**Comment by mushtaq99** [comment]
i am using this inside my android project

**Comment by sidorares** [comment]
How do you communicate with this library? This is just a thin simple http api wrapper, IMO in java environment easier to wrap with java code

**Comment by mushtaq99** [comment]
sir everything is fine just the issue with the order i can't figure out to alphabetical order 
of return HashMap

**Comment by sidorares** [comment]
I'm not fluent in Java, probably better to ask @ stackoverflow

**Comment by mushtaq99** [comment]
ok thanks for the feedback.
