### ISSUE TITLE
getLangs

### ISSUE THREAD

**Issue by Mobilpadde** [sidorares/yandex-translate#4]
API key is needed to get all languages, but the option for to set a key is missing.

Also, you'd do something like in this [module](https://www.npmjs.com/package/google-translate), where they're doing a `require("google-translate")(apiKey)`, that'd be awesome...thanks!

**Comment by sidorares** [comment]
Thanks for feedback! I think back then when I wrote this `getLangs` worked without key.
And yes, I think we can have api similar to `require("google-translate")(apiKey)` without braking existing code

**Comment by sidorares** [comment]
added in v2.0.0 ( please try gin, not in npm yet )

**Comment by Mobilpadde** [comment]
Awesome, thanks! But when will this be available on npm?

**Comment by sidorares** [comment]
pushed to npm v2.0.1 ( feel free to add more documentation to readme if you are actually using this package! )

**Comment by Mobilpadde** [comment]
Awesome, thanks! :D
