### ISSUE TITLE
Library does not work at all

### ISSUE THREAD

**Issue by unrealsolver** [sidorares/yandex-translate#5]
`require('yandex-translate')` returns `undefined`.

**Comment by sidorares** [comment]
interesting that that was there for a while. I'm pretty sure "export" was alias to "exports" in older versions of node. Which version are you using?

**Comment by unrealsolver** [comment]
I'm using 0.10. I checked documentation for `module.export` and didn't find anything.
0.8: https://nodejs.org/docs/v0.8.0/api/modules.html#modules_module_exports
0.12: https://nodejs.org/api/modules.html#modules_module_exports
